### ISSUE TITLE
Ionicons v4 download links broken

### ISSUE THREAD

**Issue by dotNetkow** [ionic-team/ionicons-site#5]
On the dedicated v4 page, https://ionicons.com/v4/, scroll to the icon list, click on an icon, then click the Material Style or iOS Style button - the download fails:

![image](https://user-images.githubusercontent.com/2545368/87974971-8a24f280-ca90-11ea-9f84-6620b319f6b2.png)

Path likely should change from: /ionicons/svg/${s}.svg to /v4/ionicons/svg/${s}.svg

Also, review PR #4 as potential fix

**Comment by thanaoat** [comment]
If you want to download svg, you can work around this bug by changing path to https://unpkg.com/ionicons@4.0.0/dist/svg/...

For example, url for arrow-down is https://ionic.io/ionicons/svg/md-arrow-down.svg
Change it to https://unpkg.com/ionicons@4.0.0/dist/svg/md-arrow-down.svg
